apiVersion: v1
kind: Service 
metadata: 
  name: covid-info
spec: 
  selector:
    app: covid-info
  ports:
    - port: 80  
      targetPort: 80
      nodePort: 30002 
      name: http
  type: NodePort
