server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/verizon_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true