server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway-server


  cloud:
    gateway:
      routes:
        - id: product-service
          uri:
            lb://product-service
          predicates:
            - Path=/api/products/**

        - id: cart-service
          uri:
            lb://cart-service
          predicates:
            - Path=/api/cart/**




